#! /usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2011 ~ 2012 Deepin, Inc.
#               2011 ~ 2012 Wang Yong
# 
# Author:     Wang Yong <lazycat.manatee@gmail.com>
# Maintainer: Wang Yong <lazycat.manatee@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import xcb
import xcb.xproto as xproto

def get_font_gc(connection, screen, window, font_name):
    font = connection.generate_id()
    cookie_font = connection.core.OpenFontChecked(
        font, 
        len(font_name),
        font_name,
        )
    xcb.xcb.Cookie.check(cookie_font)
    
    gc = connection.generate_id()
    mask = xproto.GC.Foreground | xproto.GC.Background | xproto.GC.Font
    value_list = [screen.black_pixel,
                  screen.white_pixel,
                  font,
                  ]
    
    cookie_gc = connection.core.CreateGCChecked(gc, window, mask, value_list)
    xcb.xcb.Cookie.check(cookie_gc)    
    
    cookie_font = connection.core.CloseFontChecked(font)
    xcb.xcb.Cookie.check(cookie_font)
    
    return gc

def text_draw(connection, screen, window, x, y, text):
    gc = get_font_gc(connection, screen, window, "7x13")
    cookie_text = connection.core.ImageText8Checked(len(text), window, gc, x, y, text)
    xcb.xcb.Cookie.check(cookie_text)
    
    connection.core.FreeGC(gc)

conn = xcb.connect()

# Get screen size
screen = conn.get_setup().roots[0]
screen_width = screen.width_in_pixels
screen_height = screen.height_in_pixels

# In XCB, window is uint32 id.
# We use function `generate_id` to generate id for new window. 
window = conn.generate_id()

# Create window.
cookie_window = conn.core.CreateWindowChecked(
    screen.root_depth,          # depth same as root
    window,                     # window id generated by function `generate_id`
    screen.root,                # parent window is root window
    10,                         # window x
    10,                         # window y
    screen_width / 2,           # window width
    screen_height / 2,          # window height
    30,                          # border width
    xproto.WindowClass.InputOutput, # window class
    screen.root_visual,             # window visual
    xproto.CW.BackPixel | xproto.CW.EventMask, # event mask
    [screen.white_pixel, xproto.EventMask.ButtonPress | xproto.EventMask.KeyRelease | xproto.EventMask.PointerMotion | xproto.EventMask.Exposure],
    )
xcb.xcb.Cookie.check(cookie_window)

# All window is invisible when it created.
# We need use function MapWindow to draw it on screen.
conn.core.MapWindow(window)

# Flush all X requests to the X server.
conn.flush()            

while True:
    try:
        event = conn.poll_for_event()
    except xcb.ProtocolException, error:
        print "Protocol error %s received!" % error.__class__.__name__
        break
    except:
        break
    
    if isinstance(event, xproto.KeyReleaseEvent):
        # If press ESC key.
        if event.detail == 9:
            break
    elif isinstance(event, xproto.ExposeEvent):
        text_draw(conn, screen, window, 10, 90, "Press ESC key to exit...")
        
    conn.flush()

# We should disconnect connection when don't need it anymore.
conn.disconnect()
