#! /usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2011 ~ 2012 Deepin, Inc.
#               2011 ~ 2012 Wang Yong
# 
# Author:     Wang Yong <lazycat.manatee@gmail.com>
# Maintainer: Wang Yong <lazycat.manatee@gmail.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import xcb
import xcb.xproto as xproto

conn = xcb.connect()

# Get screen size
screen = conn.get_setup().roots[0]
screen_width = screen.width_in_pixels
screen_height = screen.height_in_pixels

# In XCB, window is uint32 id.
# We use function `generate_id` to generate id for new window. 
win_id = conn.generate_id()

# Create window.
conn.core.CreateWindow(
    screen.root_depth,          # depth same as root
    win_id,                     # window id generated by function `generate_id`
    screen.root,                # parent window is root window
    10,                         # window x
    10,                         # window y
    screen_width / 2,           # window width
    screen_height / 2,          # window height
    0,                          # border width
    xproto.WindowClass.InputOutput, # window class
    screen.root_visual,             # window visual
    xproto.CW.BackPixel | xproto.CW.EventMask, # event mask
    [screen.white_pixel, xproto.EventMask.ButtonPress | xproto.EventMask.EnterWindow | xproto.EventMask.LeaveWindow | xproto.EventMask.Exposure],
    )

# Change title.
title = "Deepin XCB"
conn.core.ChangeProperty(
    xproto.PropMode.Replace,
    win_id,
    xproto.Atom.WM_NAME,
    xproto.Atom.STRING,
    8,
    len(title),
    title,
    )

conn.core.ChangeProperty(
    xproto.PropMode.Replace,
    win_id,
    xproto.Atom.WM_ICON_NAME,
    xproto.Atom.STRING,
    8,
    len(title),
    title,
    )

# All window is invisible when it created.
# We need use function MapWindow to draw it on screen.
conn.core.MapWindow(win_id)

# Flush all X requests to the X server.
conn.flush()            

while True:
    try:
        event = conn.wait_for_event()
    except xcb.ProtocolException, error:
        print "Protocol error %s received!" % error.__class__.__name__
        break
    except:
        break
    
    if isinstance(event, xproto.ButtonPressEvent):
        print "Click button to exit"
        break
        
    conn.flush()

# We should disconnect connection when don't need it anymore.
conn.disconnect()
